### ISSUE TITLE
Не работает функция crl.getRevokedCertificateSerial()

### ISSUE THREAD

**Issue by nshdigt** [TrustedPlus/trusted-crypto#10]
Пример такой в тестах, зависает
crl1 = trusted.pki.Crl.load(DEFAULT_RESOURCES_PATH + "/test.crl");
var cert2 = trusted.pki.Certificate.load(DEFAULT_RESOURCES_PATH + "/test.crt");
var cert3 = crl1.getRevokedCertificateSerial(cert2.serialNumber);

**Comment by algv** [comment]
https://github.com/TrustedPlus/trusted-crypto/commit/9f6b1b5ad83b6c7f483b482a1582d3e56f05e634

Добавил классы Revoked and RevokedCollection для работы со структурой X509_REVOKED (старое api удалил)

Пример:
```js
crl = trusted.pki.Crl.load("test.crl");
rvst = crl.revoked; 
rv = rvst.items(0);

rv.revocationDate; /*"Apr  7 20:43:24 2011 GMT"*/
rv.reason;  /*0*/
```
