### ISSUE TITLE
Не создается symlink для пакета trusted-nodejs

### ISSUE THREAD

**Issue by ilya2306** [TrustedPlus/trusted-crypto#13]
Чтобы запустить приложение, необходимо перейти в директорию ("usr/share/trusted-nodejs").
Было бы удобнее, если будет создан symlink для запуска приложения из любой директории.
`ln -s /usr/share/trusted-nodejs/trusted-nodejs /usr/local/bin`

**Comment by algv** [comment]
`npm link trusted-crypto` will create a symlink from the local node_modules folder to the global symlink.
