### ISSUE TITLE
Экспорт в PEM

### ISSUE THREAD

**Issue by microshine** [TrustedPlus/trusted-crypto#3]
`CertificationRequest::getPEMString` - функция возвращает содержимое `CertificationRequest` в PEM формате. Может имеет смысл привести эту функцию к общему интерфейсу импорта/экспорта ASN1 структур?

[Пример кода](https://github.com/Digt/trusted-crypto/blob/master/src/wrapper/pki/cert.h#L38-L39)

**Comment by SerjiEvg** [comment]
Тогда нужно ввести класс работы с ASN структурами, мы тогда это отложили.
