### ISSUE TITLE
tsd модуль устарел

### ISSUE THREAD

**Issue by microshine** [TrustedPlus/trusted-crypto#5]
`tsd` модуль является устаревшим, лучше использовать модуль `typings`

```
> sudo npm install typings -g
```
 
![image](https://cloud.githubusercontent.com/assets/7333669/17981441/747babb4-6b0c-11e6-8303-2110d2e22d4f.png)

**Comment by algv** [comment]
Обновил модуль 20584f2a4c044c2d51bfc7d11f5813f605a790f8 и настройки 7c95e62d2a3a3c2e82635b546bcc9705e0968d88
